services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      target: development
    volumes:
      - ./apps/api/src:/app/apps/api/src
      - ./packages:/app/packages
    command: bun run dev:api

  app:
    build:
      context: .
      dockerfile: apps/app/Dockerfile
      target: development
    volumes:
      - ./apps/app/src:/app/apps/app/src
      - ./packages:/app/packages
    command: bun run dev:app
