/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestMapRouteImport } from './routes/test-map'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as DashboardSessionsIndexRouteImport } from './routes/dashboard/sessions/index'
import { Route as DashboardProfitIndexRouteImport } from './routes/dashboard/profit/index'
import { Route as DashboardLiveMapIndexRouteImport } from './routes/dashboard/live-map/index'
import { Route as DashboardLicenseIndexRouteImport } from './routes/dashboard/license/index'
import { Route as DashboardCompareIndexRouteImport } from './routes/dashboard/compare/index'
import { Route as DashboardCharactersIndexRouteImport } from './routes/dashboard/characters/index'
import { Route as DashboardAnalyticsIndexRouteImport } from './routes/dashboard/analytics/index'
import { Route as DashboardSessionsSessionIdRouteImport } from './routes/dashboard/sessions/$sessionId'
import { Route as DashboardCharactersCharacterIdRouteImport } from './routes/dashboard/characters/$characterId'

const TestMapRoute = TestMapRouteImport.update({
  id: '/test-map',
  path: '/test-map',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSessionsIndexRoute = DashboardSessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfitIndexRoute = DashboardProfitIndexRouteImport.update({
  id: '/profit/',
  path: '/profit/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLiveMapIndexRoute = DashboardLiveMapIndexRouteImport.update({
  id: '/live-map/',
  path: '/live-map/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLicenseIndexRoute = DashboardLicenseIndexRouteImport.update({
  id: '/license/',
  path: '/license/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCompareIndexRoute = DashboardCompareIndexRouteImport.update({
  id: '/compare/',
  path: '/compare/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCharactersIndexRoute =
  DashboardCharactersIndexRouteImport.update({
    id: '/characters/',
    path: '/characters/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAnalyticsIndexRoute = DashboardAnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSessionsSessionIdRoute =
  DashboardSessionsSessionIdRouteImport.update({
    id: '/sessions/$sessionId',
    path: '/sessions/$sessionId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCharactersCharacterIdRoute =
  DashboardCharactersCharacterIdRouteImport.update({
    id: '/characters/$characterId',
    path: '/characters/$characterId',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/test-map': typeof TestMapRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/characters/$characterId': typeof DashboardCharactersCharacterIdRoute
  '/dashboard/sessions/$sessionId': typeof DashboardSessionsSessionIdRoute
  '/dashboard/analytics/': typeof DashboardAnalyticsIndexRoute
  '/dashboard/characters/': typeof DashboardCharactersIndexRoute
  '/dashboard/compare/': typeof DashboardCompareIndexRoute
  '/dashboard/license/': typeof DashboardLicenseIndexRoute
  '/dashboard/live-map/': typeof DashboardLiveMapIndexRoute
  '/dashboard/profit/': typeof DashboardProfitIndexRoute
  '/dashboard/sessions/': typeof DashboardSessionsIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/test-map': typeof TestMapRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/characters/$characterId': typeof DashboardCharactersCharacterIdRoute
  '/dashboard/sessions/$sessionId': typeof DashboardSessionsSessionIdRoute
  '/dashboard/analytics': typeof DashboardAnalyticsIndexRoute
  '/dashboard/characters': typeof DashboardCharactersIndexRoute
  '/dashboard/compare': typeof DashboardCompareIndexRoute
  '/dashboard/license': typeof DashboardLicenseIndexRoute
  '/dashboard/live-map': typeof DashboardLiveMapIndexRoute
  '/dashboard/profit': typeof DashboardProfitIndexRoute
  '/dashboard/sessions': typeof DashboardSessionsIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/test-map': typeof TestMapRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/characters/$characterId': typeof DashboardCharactersCharacterIdRoute
  '/dashboard/sessions/$sessionId': typeof DashboardSessionsSessionIdRoute
  '/dashboard/analytics/': typeof DashboardAnalyticsIndexRoute
  '/dashboard/characters/': typeof DashboardCharactersIndexRoute
  '/dashboard/compare/': typeof DashboardCompareIndexRoute
  '/dashboard/license/': typeof DashboardLicenseIndexRoute
  '/dashboard/live-map/': typeof DashboardLiveMapIndexRoute
  '/dashboard/profit/': typeof DashboardProfitIndexRoute
  '/dashboard/sessions/': typeof DashboardSessionsIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/test-map'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/'
    | '/dashboard/characters/$characterId'
    | '/dashboard/sessions/$sessionId'
    | '/dashboard/analytics/'
    | '/dashboard/characters/'
    | '/dashboard/compare/'
    | '/dashboard/license/'
    | '/dashboard/live-map/'
    | '/dashboard/profit/'
    | '/dashboard/sessions/'
    | '/dashboard/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/test-map'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard'
    | '/dashboard/characters/$characterId'
    | '/dashboard/sessions/$sessionId'
    | '/dashboard/analytics'
    | '/dashboard/characters'
    | '/dashboard/compare'
    | '/dashboard/license'
    | '/dashboard/live-map'
    | '/dashboard/profit'
    | '/dashboard/sessions'
    | '/dashboard/settings'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/test-map'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/'
    | '/dashboard/characters/$characterId'
    | '/dashboard/sessions/$sessionId'
    | '/dashboard/analytics/'
    | '/dashboard/characters/'
    | '/dashboard/compare/'
    | '/dashboard/license/'
    | '/dashboard/live-map/'
    | '/dashboard/profit/'
    | '/dashboard/sessions/'
    | '/dashboard/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  TestMapRoute: typeof TestMapRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-map': {
      id: '/test-map'
      path: '/test-map'
      fullPath: '/test-map'
      preLoaderRoute: typeof TestMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sessions/': {
      id: '/dashboard/sessions/'
      path: '/sessions'
      fullPath: '/dashboard/sessions/'
      preLoaderRoute: typeof DashboardSessionsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profit/': {
      id: '/dashboard/profit/'
      path: '/profit'
      fullPath: '/dashboard/profit/'
      preLoaderRoute: typeof DashboardProfitIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/live-map/': {
      id: '/dashboard/live-map/'
      path: '/live-map'
      fullPath: '/dashboard/live-map/'
      preLoaderRoute: typeof DashboardLiveMapIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/license/': {
      id: '/dashboard/license/'
      path: '/license'
      fullPath: '/dashboard/license/'
      preLoaderRoute: typeof DashboardLicenseIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/compare/': {
      id: '/dashboard/compare/'
      path: '/compare'
      fullPath: '/dashboard/compare/'
      preLoaderRoute: typeof DashboardCompareIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/characters/': {
      id: '/dashboard/characters/'
      path: '/characters'
      fullPath: '/dashboard/characters/'
      preLoaderRoute: typeof DashboardCharactersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics/': {
      id: '/dashboard/analytics/'
      path: '/analytics'
      fullPath: '/dashboard/analytics/'
      preLoaderRoute: typeof DashboardAnalyticsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sessions/$sessionId': {
      id: '/dashboard/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/dashboard/sessions/$sessionId'
      preLoaderRoute: typeof DashboardSessionsSessionIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/characters/$characterId': {
      id: '/dashboard/characters/$characterId'
      path: '/characters/$characterId'
      fullPath: '/dashboard/characters/$characterId'
      preLoaderRoute: typeof DashboardCharactersCharacterIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCharactersCharacterIdRoute: typeof DashboardCharactersCharacterIdRoute
  DashboardSessionsSessionIdRoute: typeof DashboardSessionsSessionIdRoute
  DashboardAnalyticsIndexRoute: typeof DashboardAnalyticsIndexRoute
  DashboardCharactersIndexRoute: typeof DashboardCharactersIndexRoute
  DashboardCompareIndexRoute: typeof DashboardCompareIndexRoute
  DashboardLicenseIndexRoute: typeof DashboardLicenseIndexRoute
  DashboardLiveMapIndexRoute: typeof DashboardLiveMapIndexRoute
  DashboardProfitIndexRoute: typeof DashboardProfitIndexRoute
  DashboardSessionsIndexRoute: typeof DashboardSessionsIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCharactersCharacterIdRoute: DashboardCharactersCharacterIdRoute,
  DashboardSessionsSessionIdRoute: DashboardSessionsSessionIdRoute,
  DashboardAnalyticsIndexRoute: DashboardAnalyticsIndexRoute,
  DashboardCharactersIndexRoute: DashboardCharactersIndexRoute,
  DashboardCompareIndexRoute: DashboardCompareIndexRoute,
  DashboardLicenseIndexRoute: DashboardLicenseIndexRoute,
  DashboardLiveMapIndexRoute: DashboardLiveMapIndexRoute,
  DashboardProfitIndexRoute: DashboardProfitIndexRoute,
  DashboardSessionsIndexRoute: DashboardSessionsIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  TestMapRoute: TestMapRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
