import { DataSource } from "typeorm";
import { env } from "./env.js";
import {
  UserEntity,
  PlanEntity,
  SubscriptionEntity,
  LicenseKeyEntity,
  CharacterEntity,
  SessionEntity,
  KillEntity,
  LootEntity,
  ExperienceSnapshotEntity,
  PositionLogEntity,
  DiscordIntegrationEntity,
  RouteEntity,
  GameEventEntity,
  BotConfigEntity,
  FeatureFlagEntity,
  SystemSettingEntity,
} from "../entities/index.js";

export const dataSource = new DataSource({
  type: "postgres",
  host: env.DATABASE_HOST,
  port: env.DATABASE_PORT,
  username: env.DATABASE_USER,
  password: env.DATABASE_PASSWORD,
  database: env.DATABASE_NAME,
  entities: [
    UserEntity,
    PlanEntity,
    SubscriptionEntity,
    LicenseKeyEntity,
    CharacterEntity,
    SessionEntity,
    KillEntity,
    LootEntity,
    ExperienceSnapshotEntity,
    PositionLogEntity,
    DiscordIntegrationEntity,
    RouteEntity,
    GameEventEntity,
    BotConfigEntity,
    FeatureFlagEntity,
    SystemSettingEntity,
  ],
  synchronize: env.NODE_ENV === "development",
  migrations: ["dist/migrations/*.js"],
  migrationsRun: env.NODE_ENV === "production",
  logging: env.NODE_ENV === "development",
});
