/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as DashboardUsersIndexRouteImport } from './routes/dashboard/users/index'
import { Route as DashboardSubscriptionsIndexRouteImport } from './routes/dashboard/subscriptions/index'
import { Route as DashboardLicensesIndexRouteImport } from './routes/dashboard/licenses/index'
import { Route as DashboardApiKeysIndexRouteImport } from './routes/dashboard/api-keys/index'
import { Route as DashboardUsersIdRouteImport } from './routes/dashboard/users/$id'
import { Route as DashboardSubscriptionsRevenueRouteImport } from './routes/dashboard/subscriptions/revenue'
import { Route as DashboardSubscriptionsPlansRouteImport } from './routes/dashboard/subscriptions/plans'
import { Route as DashboardSettingsPricingRouteImport } from './routes/dashboard/settings/pricing'
import { Route as DashboardSettingsFeaturesRouteImport } from './routes/dashboard/settings/features'
import { Route as DashboardAnalyticsUsageRouteImport } from './routes/dashboard/analytics/usage'
import { Route as DashboardAnalyticsPerformanceRouteImport } from './routes/dashboard/analytics/performance'
import { Route as DashboardAnalyticsBotsOnlineRouteImport } from './routes/dashboard/analytics/bots-online'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUsersIndexRoute = DashboardUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSubscriptionsIndexRoute =
  DashboardSubscriptionsIndexRouteImport.update({
    id: '/subscriptions/',
    path: '/subscriptions/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardLicensesIndexRoute = DashboardLicensesIndexRouteImport.update({
  id: '/licenses/',
  path: '/licenses/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApiKeysIndexRoute = DashboardApiKeysIndexRouteImport.update({
  id: '/api-keys/',
  path: '/api-keys/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersIdRoute = DashboardUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSubscriptionsRevenueRoute =
  DashboardSubscriptionsRevenueRouteImport.update({
    id: '/subscriptions/revenue',
    path: '/subscriptions/revenue',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSubscriptionsPlansRoute =
  DashboardSubscriptionsPlansRouteImport.update({
    id: '/subscriptions/plans',
    path: '/subscriptions/plans',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsPricingRoute =
  DashboardSettingsPricingRouteImport.update({
    id: '/settings/pricing',
    path: '/settings/pricing',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsFeaturesRoute =
  DashboardSettingsFeaturesRouteImport.update({
    id: '/settings/features',
    path: '/settings/features',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAnalyticsUsageRoute = DashboardAnalyticsUsageRouteImport.update({
  id: '/analytics/usage',
  path: '/analytics/usage',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsPerformanceRoute =
  DashboardAnalyticsPerformanceRouteImport.update({
    id: '/analytics/performance',
    path: '/analytics/performance',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAnalyticsBotsOnlineRoute =
  DashboardAnalyticsBotsOnlineRouteImport.update({
    id: '/analytics/bots-online',
    path: '/analytics/bots-online',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/analytics/bots-online': typeof DashboardAnalyticsBotsOnlineRoute
  '/dashboard/analytics/performance': typeof DashboardAnalyticsPerformanceRoute
  '/dashboard/analytics/usage': typeof DashboardAnalyticsUsageRoute
  '/dashboard/settings/features': typeof DashboardSettingsFeaturesRoute
  '/dashboard/settings/pricing': typeof DashboardSettingsPricingRoute
  '/dashboard/subscriptions/plans': typeof DashboardSubscriptionsPlansRoute
  '/dashboard/subscriptions/revenue': typeof DashboardSubscriptionsRevenueRoute
  '/dashboard/users/$id': typeof DashboardUsersIdRoute
  '/dashboard/api-keys/': typeof DashboardApiKeysIndexRoute
  '/dashboard/licenses/': typeof DashboardLicensesIndexRoute
  '/dashboard/subscriptions/': typeof DashboardSubscriptionsIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/analytics/bots-online': typeof DashboardAnalyticsBotsOnlineRoute
  '/dashboard/analytics/performance': typeof DashboardAnalyticsPerformanceRoute
  '/dashboard/analytics/usage': typeof DashboardAnalyticsUsageRoute
  '/dashboard/settings/features': typeof DashboardSettingsFeaturesRoute
  '/dashboard/settings/pricing': typeof DashboardSettingsPricingRoute
  '/dashboard/subscriptions/plans': typeof DashboardSubscriptionsPlansRoute
  '/dashboard/subscriptions/revenue': typeof DashboardSubscriptionsRevenueRoute
  '/dashboard/users/$id': typeof DashboardUsersIdRoute
  '/dashboard/api-keys': typeof DashboardApiKeysIndexRoute
  '/dashboard/licenses': typeof DashboardLicensesIndexRoute
  '/dashboard/subscriptions': typeof DashboardSubscriptionsIndexRoute
  '/dashboard/users': typeof DashboardUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/analytics/bots-online': typeof DashboardAnalyticsBotsOnlineRoute
  '/dashboard/analytics/performance': typeof DashboardAnalyticsPerformanceRoute
  '/dashboard/analytics/usage': typeof DashboardAnalyticsUsageRoute
  '/dashboard/settings/features': typeof DashboardSettingsFeaturesRoute
  '/dashboard/settings/pricing': typeof DashboardSettingsPricingRoute
  '/dashboard/subscriptions/plans': typeof DashboardSubscriptionsPlansRoute
  '/dashboard/subscriptions/revenue': typeof DashboardSubscriptionsRevenueRoute
  '/dashboard/users/$id': typeof DashboardUsersIdRoute
  '/dashboard/api-keys/': typeof DashboardApiKeysIndexRoute
  '/dashboard/licenses/': typeof DashboardLicensesIndexRoute
  '/dashboard/subscriptions/': typeof DashboardSubscriptionsIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/auth/login'
    | '/dashboard/'
    | '/dashboard/analytics/bots-online'
    | '/dashboard/analytics/performance'
    | '/dashboard/analytics/usage'
    | '/dashboard/settings/features'
    | '/dashboard/settings/pricing'
    | '/dashboard/subscriptions/plans'
    | '/dashboard/subscriptions/revenue'
    | '/dashboard/users/$id'
    | '/dashboard/api-keys/'
    | '/dashboard/licenses/'
    | '/dashboard/subscriptions/'
    | '/dashboard/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/dashboard'
    | '/dashboard/analytics/bots-online'
    | '/dashboard/analytics/performance'
    | '/dashboard/analytics/usage'
    | '/dashboard/settings/features'
    | '/dashboard/settings/pricing'
    | '/dashboard/subscriptions/plans'
    | '/dashboard/subscriptions/revenue'
    | '/dashboard/users/$id'
    | '/dashboard/api-keys'
    | '/dashboard/licenses'
    | '/dashboard/subscriptions'
    | '/dashboard/users'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/auth/login'
    | '/dashboard/'
    | '/dashboard/analytics/bots-online'
    | '/dashboard/analytics/performance'
    | '/dashboard/analytics/usage'
    | '/dashboard/settings/features'
    | '/dashboard/settings/pricing'
    | '/dashboard/subscriptions/plans'
    | '/dashboard/subscriptions/revenue'
    | '/dashboard/users/$id'
    | '/dashboard/api-keys/'
    | '/dashboard/licenses/'
    | '/dashboard/subscriptions/'
    | '/dashboard/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/users/': {
      id: '/dashboard/users/'
      path: '/users'
      fullPath: '/dashboard/users/'
      preLoaderRoute: typeof DashboardUsersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/subscriptions/': {
      id: '/dashboard/subscriptions/'
      path: '/subscriptions'
      fullPath: '/dashboard/subscriptions/'
      preLoaderRoute: typeof DashboardSubscriptionsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/licenses/': {
      id: '/dashboard/licenses/'
      path: '/licenses'
      fullPath: '/dashboard/licenses/'
      preLoaderRoute: typeof DashboardLicensesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/api-keys/': {
      id: '/dashboard/api-keys/'
      path: '/api-keys'
      fullPath: '/dashboard/api-keys/'
      preLoaderRoute: typeof DashboardApiKeysIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users/$id': {
      id: '/dashboard/users/$id'
      path: '/users/$id'
      fullPath: '/dashboard/users/$id'
      preLoaderRoute: typeof DashboardUsersIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/subscriptions/revenue': {
      id: '/dashboard/subscriptions/revenue'
      path: '/subscriptions/revenue'
      fullPath: '/dashboard/subscriptions/revenue'
      preLoaderRoute: typeof DashboardSubscriptionsRevenueRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/subscriptions/plans': {
      id: '/dashboard/subscriptions/plans'
      path: '/subscriptions/plans'
      fullPath: '/dashboard/subscriptions/plans'
      preLoaderRoute: typeof DashboardSubscriptionsPlansRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/pricing': {
      id: '/dashboard/settings/pricing'
      path: '/settings/pricing'
      fullPath: '/dashboard/settings/pricing'
      preLoaderRoute: typeof DashboardSettingsPricingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/features': {
      id: '/dashboard/settings/features'
      path: '/settings/features'
      fullPath: '/dashboard/settings/features'
      preLoaderRoute: typeof DashboardSettingsFeaturesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics/usage': {
      id: '/dashboard/analytics/usage'
      path: '/analytics/usage'
      fullPath: '/dashboard/analytics/usage'
      preLoaderRoute: typeof DashboardAnalyticsUsageRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics/performance': {
      id: '/dashboard/analytics/performance'
      path: '/analytics/performance'
      fullPath: '/dashboard/analytics/performance'
      preLoaderRoute: typeof DashboardAnalyticsPerformanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics/bots-online': {
      id: '/dashboard/analytics/bots-online'
      path: '/analytics/bots-online'
      fullPath: '/dashboard/analytics/bots-online'
      preLoaderRoute: typeof DashboardAnalyticsBotsOnlineRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAnalyticsBotsOnlineRoute: typeof DashboardAnalyticsBotsOnlineRoute
  DashboardAnalyticsPerformanceRoute: typeof DashboardAnalyticsPerformanceRoute
  DashboardAnalyticsUsageRoute: typeof DashboardAnalyticsUsageRoute
  DashboardSettingsFeaturesRoute: typeof DashboardSettingsFeaturesRoute
  DashboardSettingsPricingRoute: typeof DashboardSettingsPricingRoute
  DashboardSubscriptionsPlansRoute: typeof DashboardSubscriptionsPlansRoute
  DashboardSubscriptionsRevenueRoute: typeof DashboardSubscriptionsRevenueRoute
  DashboardUsersIdRoute: typeof DashboardUsersIdRoute
  DashboardApiKeysIndexRoute: typeof DashboardApiKeysIndexRoute
  DashboardLicensesIndexRoute: typeof DashboardLicensesIndexRoute
  DashboardSubscriptionsIndexRoute: typeof DashboardSubscriptionsIndexRoute
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAnalyticsBotsOnlineRoute: DashboardAnalyticsBotsOnlineRoute,
  DashboardAnalyticsPerformanceRoute: DashboardAnalyticsPerformanceRoute,
  DashboardAnalyticsUsageRoute: DashboardAnalyticsUsageRoute,
  DashboardSettingsFeaturesRoute: DashboardSettingsFeaturesRoute,
  DashboardSettingsPricingRoute: DashboardSettingsPricingRoute,
  DashboardSubscriptionsPlansRoute: DashboardSubscriptionsPlansRoute,
  DashboardSubscriptionsRevenueRoute: DashboardSubscriptionsRevenueRoute,
  DashboardUsersIdRoute: DashboardUsersIdRoute,
  DashboardApiKeysIndexRoute: DashboardApiKeysIndexRoute,
  DashboardLicensesIndexRoute: DashboardLicensesIndexRoute,
  DashboardSubscriptionsIndexRoute: DashboardSubscriptionsIndexRoute,
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
